### ISSUE TITLE
Crash when scrolling over SimplySkills Agile effect

### ISSUE THREAD

**Issue by Partonetrain** [TheWinABagel/ZenithAttributes#27]
```
Stacktrace:
	at dev.shadowsoffire.attributeslib.api.IFormattableAttribute.toComponent(IFormattableAttribute.java:196)
	at dev.shadowsoffire.attributeslib.client.AttributesLibClient.lambda$effectGuiTooltips$3(AttributesLibClient.java:138)
	at dev.shadowsoffire.attributeslib.api.client.GatherEffectScreenTooltipsEvent.lambda$static$0(GatherEffectScreenTooltipsEvent.java:20)
	at net.minecraft.class_485.args$kfl000$zenith_attributes$ModifyRenderEffectsArgs(class_485.java:522)
	at net.minecraft.class_485.method_2477(class_485.java:73)
	at net.minecraft.class_485.method_25394(class_485.java:28)
	at net.minecraft.class_490.method_25394(class_490.java:88)
	at net.minecraft.class_437.method_47413(class_437.java:110)
	at net.minecraft.class_757.mixinextras$bridge$method_47413$225(class_757.java)
	at net.minecraft.class_757.wrapOperation$fja000$fancymenu$wrapRenderScreenFancyMenu(class_757.java:6607)
	at net.minecraft.class_757.mixinextras$bridge$wrapOperation$fja000$fancymenu$wrapRenderScreenFancyMenu$226(class_757.java)
	at net.minecraft.class_757.wrapOperation$fpg000$konkrete$wrapRenderScreenKonkrete(class_757.java:7106)

-- Screen render details --
Details:
	Screen name: net.minecraft.class_490
	Mouse location: Scaled: (347, 111). Absolute: (1388.000000, 443.000000)
	Screen size: Scaled: (480, 255). Absolute: (1920, 1017). Scale factor of 4.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:945)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```
I added some null checks which prevented the crash, but I didn't really understand the cause of the problem so it's not really a solution

**Comment by Partonetrain** [comment]
No longer an issue as of SimplySkills 1.5.0
