### ISSUE TITLE
Public api change in patch version

### ISSUE THREAD

**Issue by solonovamax** [TheWinABagel/ZenithAttributes#4]
There is a change to the public api in the latest patch version: https://github.com/TheWinABagel/ZenithAttributes/commit/6ae46288629ab50bc1d0d6b0f1527e324834d138#diff-3b0d92c24d7f0204d61eb48717e5a9e7705b48bf4cb84261356437241c545e6aL50

This causes zenith to break if zenith attributes is updated:
```
Caused by: java.lang.NoSuchFieldError: Class dev.shadowsoffire.attributeslib.AttributesLib does not have member field 'java.util.List playerAttributes'
	at dev.shadowsoffire.apotheosis.adventure.affix.socket.gem.bonus.special.AllStatsBonus.<init>(AllStatsBonus.java:51) ~[zenith-0.2.3-1.20.1.jar:?]
	at com.mojang.serialization.DataResult$Instance.ap3(DataResult.java:340) ~[datafixerupper-6.0.8.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$5.decode(RecordCodecBuilder.java:321) ~[datafixerupper-6.0.8.jar:?]
```

Minecraft will not permit you to load worlds, due to these errors.

**Comment by TheWinABagel** [comment]
Was fixed a while ago, forgot to close
