### ISSUE TITLE
Unregistered DummyTrinket in non-Dev environment causing crash

### ISSUE THREAD

**Issue by Partonetrain** [TheWinABagel/ZenithAttributes#6]
The game crashes on start with zenithattributes 0.1.4 in production environment because DummyTrinket isn't registered.

Using [Silverfish](https://github.com/Daomephsta/silverfish) we can see the cause:
[16:19:34] [Render thread/INFO]: No origin traces for [dev.shadowsoffire.attributeslib.util.DummyTrinket{not yet registered, hashCode 468a6ca2}] (originTracing.classes is empty)
[16:19:34] [Render thread/ERROR]: Unhandled game exception
java.lang.IllegalStateException: Some intrusive holders were not registered: [Reference{null=dev.shadowsoffire.attributeslib.util.DummyTrinket{not yet registered, hashCode 468a6ca2}}]
	at net.minecraft.class_2370.method_40276(class_2370.java:364) ~[client-intermediary.jar:?]
	at net.minecraft.class_7923.method_47491(class_7923.java:239) ~[client-intermediary.jar:?]
	at net.minecraft.class_7923.method_47476(class_7923.java:223) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.handler$dac001$fabric-registry-sync-v0$onStart(class_310.java:16560) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:781) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[fabric-loader-0.15.3-1.20.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.3.jar:?]

**Comment by Partonetrain** [comment]
Also, I'd like to investigate issues in this project, but I can't import the gradle project. Is FakerLib hosted on a maven anywhere?

**Comment by Partonetrain** [comment]
Fixed in 0.1.5
